const START_GAME = "START_GAME";
const END_GAME = "END_GAME";
const UPDATE_BOARD = "UPDATE_BOARD";
const UNCOVER_CELL = "UNCOVER_CELL";
const CLICKED_BOMB = "CLICKED_BOMB";

export { START_GAME, END_GAME, UPDATE_BOARD, UNCOVER_CELL, CLICKED_BOMB };
